# Generated by Django 4.0.4 on 2023-01-14 07:13

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('attendenceid', models.AutoField(primary_key=True, serialize=False)),
                ('memberid', models.IntegerField()),
                ('date', models.DateField()),
                ('timein', models.CharField(max_length=20)),
                ('timeout', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('eId', models.AutoField(primary_key=True, serialize=False)),
                ('eName', models.CharField(max_length=20)),
                ('ephone', models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone number')),
                ('edate', models.DateField()),
                ('nextDate', models.DateField()),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('expid', models.AutoField(primary_key=True, serialize=False)),
                ('expAmt', models.IntegerField()),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('memberid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='email@gmail.com', max_length=40, unique=True)),
                ('phone', models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone number')),
                ('altphone', models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Alternate Phone number')),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('billingid', models.AutoField(primary_key=True, serialize=False)),
                ('memberid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=10)),
                ('startDate', models.DateField()),
                ('endPlanDate', models.DateField()),
                ('paymentMode', models.CharField(max_length=10)),
                ('paidAmt', models.IntegerField()),
                ('pendingAmt', models.IntegerField()),
            ],
        ),
    ]
