# Generated by Django 4.0.4 on 2023-01-14 09:06

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_members_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='altphone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Alternate Phone number'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
